# load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "CPPLib",
    srcs = glob(["**//*.cpp"])
    hdrs = glob(["**//*.hpp"])
    # srcs =["cpplib.cc"],
    # hdrs = ["cpplib.h"],
    visibility = ["//visibility:public"],
)
